#!/bin/sh

case "`uname -s`" in
	AIX)	echo "aix"; exit 0;;
	Linux)	if rpm -q suse-release >/dev/null 2>&1; then
			echo "suse"; exit 0
		elif rpm -q redhat-release >/dev/null 2>&1; then
			echo "redhat"; exit 0
		elif rpm -q fedora-release >/dev/null 2>&1; then
			echo "redhat"; exit 0
		elif test -f /etc/debian_version; then
			if test -f /usr/bin/apxs2; then
				echo "debian-apache2"
			elif test -f /usr/bin/apxs; then
				echo "debian-apache1"
			else
				echo "debian"
			fi
			exit 0
		fi;;
	HP-UX)	echo "hpux"; exit 0;;
esac
echo "unknown"

echo "$0: can't determine platform name" >&2
exit 1

