#! /bin/sh
# (c) 2007 Quest Software, Inc. All rights reserved.
# $Id$
#
# This helper script is provided to simplify setting up mod_auth_vas
# on a basic web server. It creates the HTTP service for the computer
# (if not done), and changes ownerships on the resulting keytab.
#

KEYTAB=/etc/opt/quest/vas/HTTP.keytab
VASTOOL=/opt/quest/bin/vastool
KTUTIL=/opt/quest/bin/ktutil
LOGFILE=/tmp/mod_auth_vas-setup.log.$$

echo1 () { echo -n "$*"; }
echo2 () { echo "$*\\c"; }
echo3 () { echo "$* +"; }

if test "x`echo1 y`z" = "xyz"; then
    echon() { echo1 "$*"; }
elif test "x`echo2 y`z" = "xyz"; then
    echon () { echo2 "$*"; }
else
    echon () { echo3 "$*"; }
fi

umask 077

#-- prints a label with dots after it, and no newline
label () {
    echon "  `echo $* ............................................... | cut -c -40`  "
}

#-- prints an error message and dies
die () {
    echo "  -> Failed: $1" >&2
    exit 1
}

#-- prompt user for information
#   usage: query prompt varname [default]
query () {
    eval $2=
    while eval "test ! -n \"\$$2\""; do
	if read xx?yy <$0 2>/dev/null; then
	    eval "read \"$2?$1${3+ [$3]}: \"" || die "(end of file)"
	else
	    eval "read -p \"$1${3+ [$3]}: \" $2" || die "(end of file)"
	fi
	eval : "\${$2:=\$3}"
    done
}

yesorno () {
    echo "";
    while :; do
	query "$1" YESORNO y
	case "$YESORNO" in
	    Y*|y*) echo; return 0;;
	    N*|n*) echo; return 1;;
	    *) echo "Please enter 'y' or 'n'" >&2;;
	esac
    done
}

logfile_written=false
recordcmd () {
    if ! $logfile_written; then
	rm -f $LOGFILE
	set -o noclobber
	exec 5>$LOGFILE 
	set +o noclobber
    	logfile_written=true
    fi
    (echo "# `date`";
    echo "$*";
    echo ) >&5
    "$@"
}

usage () {
    cat <<-.
	Usage: $0 [-a apxs] [-c conf] [-h]
	    -a apxs
	          Use program 'apxs' to find the web server extension tool.
	          If not specified, a built-in search path is used.
	    -c conf
	          Use file 'conf' as the main Apache configuration file. If
	          not specified, the apxs extension tool is queried.
	    -h
	          Display this help text.
.
}

#-- parse args

cflag=
aflag=
opterr=false

while test $# -gt 0; do
    case "$1" in
	-c)  if test $# -lt 2; then 
		echo "Missing argument to $1"; opterr=true; shift
	     else
		cflag="$2"; shift; shift
	     fi;;
	-c*) cflag=`echo " $1" | sed -e 's/^ -c//'`; shift;;
	-a)  if test $# -lt 2; then 
		echo "Missing argument to $1"; opterr=true; shift
	     else
		aflag="$2"; shift; shift
	     fi;;
	-a*) aflag=`echo " $1" | sed -e 's/^ -a//'`; shift;;
	-h)  usage; exit 0;;
	--)  shift; break;;
	-?*) echo "Unknown option: $1"; opterr=true; shift;;
	*)   break;;
    esac
done
if test $# -gt 0; then
    # don't expect any further arguments
    opterr=true
fi
if $opterr; then
    usage
    exit 1
fi

if test -n "$aflag" -a -n "$cflag"; then
    aflag=
    echo "WARNING: Ignoring -a option when -c supplied" >&2
fi

#-- intro
cat <<-.

	This script checks your local configuration for properly using mod_auth_vas.
	It will prompt you to create a web service object in Active Directory
	if one is needed, and it will correct permissions on certain files.
	Commands executed will be recorded in $LOGFILE

.

#-- tests
label "checking privileges"
id -un
if test `id -u` -ne 0; then
    checkroot () { 
	echo ""
	echo "WARNING: This script may need superuser privileges to proceed"
	echo ""
    }
else
    checkroot () { : ; }
fi

#-- look for apxs only if -c isn't supplied
apxs=
if test -z "$cflag"; then
    label "looking for Apache extension tool"
    for x in "$aflag" apxs2 apxs /usr/sbin/apxs2 /usr/sbin/apxs; do
	test -z "$x" && continue
	AP_CF=`("$x" -q SYSCONFDIR) 2>/dev/null`/apache2.conf
	test -f "$AP_CF" && apxs="$x" && break
	AP_CF=`("$x" -q SYSCONFDIR) 2>/dev/null`/httpd.conf
	test -f "$AP_CF" && apxs="$x" && break
	AP_CF=
	test x"$x" = x"$aflag" && break
    done
    if test -z "$apxs" -a -n "$aflag"; then
	echo "$aflag: not found or didn't work"
	exit 1
    elif test -z "$apxs"; then
	echo "not found"
    else
	echo "$apxs"
    fi
fi

label "looking for Apache configuration file"
if test -n "$cflag"; then
    AP_CF="$cflag"
elif test -z "$AP_CF"; then
    for dir in /etc/apache2 /etc/apache /etc/httpd/conf /etc/apache2/conf \
	/etc/apache/conf /etc/www/conf /var/www/conf /opt/IBMIHS/conf
    do
	if test -f $dir/apache2.conf; then
	    AP_CF=$dir/apache2.conf
	    break
	fi
	if test -f $dir/httpd.conf; then
	    AP_CF=$dir/httpd.conf
	    break
	fi
    done
fi

#-- scan the config file for a group name
if test -f "$AP_CF"; then
    echo "$AP_CF"
    #echo "found"
    label "looking for Apache daemon group"
    APACHE_GROUP=`(sed -ne 's/^Group //p' < "$AP_CF"|sed -e 1q) 2>/dev/null`
    if test ! -n "$APACHE_GROUP"; then
	#-- try harder 
	for path in `sed -ne 's/^Include //p' < "$AP_CF"` /dev/null; do
	    APACHE_GROUP=`(sed -ne 's/^Group //p' < "$path"|sed -e 1q) 2>/dev/null`
	    test -n "$APACHE_GROUP" && break
	done
    fi

    if test -n "$APACHE_GROUP"; then
	echo "$APACHE_GROUP"
    else
	echo "not found"
    fi
else
    APACHE_GROUP=
    if test -z "$cflag"; then
	echo "not found"
    else
	echo "$cflag: not found"
	exit 1
    fi
fi

#-- if the Apache group is still unknown, look at existing groups and guess
if test ! -n "$APACHE_GROUP"; then
    APACHE_GROUP_GUESS=nobody
    for u in apache httpd www nogroup; do
	if test x`eval echo "~$u"` != x"~$u"; then
	    APACHE_GROUP_GUESS=$u
	    break
	fi
    done
fi

label "looking for HTTP/ keytab"
if test -f "$KEYTAB"; then
    echo "$KEYTAB"
else
    echo "keytab not found"
    cat <<-.

	This step creates a service object in Active Directory so 
	that browsers can authenticate with this web server.
	You will need to know an account password that has
	sufficient privileges to create the new service object.
	Contact your systems administration staff if you do not.
.
    if yesorno "Create the HTTP/ service account?"; then
        
        echo "Please specify the container DN in which to create the service:"
        query "Service container DN" CONTAINER default
        test x"$CONTAINER" = x"default" && CONTAINER=

        echo "Please login with a domain account to create the service:"
        checkroot
        query "Username" USER Administrator

        recordcmd $VASTOOL -u "$USER" service create ${CONTAINER:+-c "$CONTAINER"} HTTP/ || \
	    die "Cannot create HTTP/ service key: contact your IT support"

	label "checking new service keytab"
	if test -f "$KEYTAB"; then 
	    echo "found"
	else
	    echo "still not found"
	    die "Cannot find $KEYTAB"
	fi
	echo ""
	$KTUTIL -k "$KEYTAB" list
	echo ""
    else
	echo "(Not creating HTTP/ service account)"
    fi
fi

if test -f "$KEYTAB"; then
  if test ! -n "$APACHE_GROUP"; then
    echo ""
    echo "The Apache server process must be able to access the keytab."
    echo "I didn't find a httpd.conf file so I don't know what creds it uses."
    echo "Tell me what unix group it will run as, and I'll check the"
    echo "keytab file permissions so that it is readable by Apache."
    echo ""
    query "Group for Apache httpd process" APACHE_GROUP $APACHE_GROUP_GUESS
    echo ""
  fi

  label "checking keytab is readable by $APACHE_GROUP"
  set -- `/bin/ls -l "$KEYTAB"`
  case "$1:$4" in
    -??????r??:*) echo "yes" ;;
    -???r?????:$APACHE_GROUP) echo "yes" ;;
    *) echo "no"
       if yesorno "Change group of $KEYTAB to $APACHE_GROUP?"; then
           label " -> fixing file mode and ownership"
           checkroot
           recordcmd chgrp "$APACHE_GROUP" "$KEYTAB" || 
	       die "Could not change file group"
           recordcmd chmod 640 "$KEYTAB" || 
	   	die "Could not change file mode"
           echo "fixed"
       else
	   echo "(Not changing ownership)"
       fi 
       ;;
  esac
fi

echo ""
$logfile_written && echo "(Log written to $LOGFILE)"
echo "Finished."
exit 0
